### ISSUE TITLE
下载时提示AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by liangffzz** [lflame/TsinghuaBookCrawler#3]
`Traceback (most recent call last):
  File "main.py", line 67, in <module>
    st, ed = re.search('(/([^/]*)/)(mobile)', url0).span(2)
AttributeError: 'NoneType' object has no attribute 'span'`

下载书籍时提示该错误，以前试用的时候没发现这个问题，是网页的参数发生了什么变化么orz

**Comment by lflame** [comment]
啊应该是出现变化了？这两天在忙推研，我尽快修复一下qaq，谢谢提醒！



---Original---
From: ***@***.***&gt;
Sent at: 2021年9月7日(Tue) Evening10:57
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [lflame/TsinghuaBookCrawler] 下载时提示AttributeError: 'NoneType' object has no attribute 'span' (#3)




 
Traceback (most recent call last): File "main.py", line 67, in <module&gt; st, ed = re.search('(/([^/]*)/)(mobile)', url0).span(2) AttributeError: 'NoneType' object has no attribute 'span'
 
下载书籍时提示该错误，以前试用的时候没发现这个问题，是网页的参数发生了什么变化么orz
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liangffzz** [comment]
> 啊应该是出现变化了？这两天在忙推研，我尽快修复一下qaq，谢谢提醒！
> […](#)
> ---Original--- From: ***@***.***&gt; Sent at: 2021年9月7日(Tue) Evening10:57 To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [lflame/TsinghuaBookCrawler] 下载时提示AttributeError: 'NoneType' object has no attribute 'span' (#3) Traceback (most recent call last): File "main.py", line 67, in <module&gt; st, ed = re.search('(/([^/]*)/)(mobile)', url0).span(2) AttributeError: 'NoneType' object has no attribute 'span' 下载书籍时提示该错误，以前试用的时候没发现这个问题，是网页的参数发生了什么变化么orz — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

啊不好意思是，刚刚仔细看了一遍说明，是我太久没用自己犯傻了orz
应该链接应该用页面下面的链接，我想当然地用了网页自己的URL = = 
重新试了一下，没有出现变化，可以正常下载，祝推研顺利！

**Comment by lflame** [comment]
啊好的好的，谢谢啦～之后遇到什么问题也可以随时联系我



---Original---
From: ***@***.***&gt;
Sent at: 2021年9月7日(Tue) Evening11:21
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lflame/TsinghuaBookCrawler] 下载时提示AttributeError: 'NoneType' object has no attribute 'span' (#3)




  
啊应该是出现变化了？这两天在忙推研，我尽快修复一下qaq，谢谢提醒！
 …
 ---Original--- From: @.&gt; Sent at: 2021年9月7日(Tue) Evening10:57 To: @.&gt;; Cc: @.**&gt;; Subject: [lflame/TsinghuaBookCrawler] 下载时提示AttributeError: 'NoneType' object has no attribute 'span' (#3) Traceback (most recent call last): File "main.py", line 67, in <module&gt; st, ed = re.search('(/([^/])/)(mobile)', url0).span(2) AttributeError: 'NoneType' object has no attribute 'span' 下载书籍时提示该错误，以前试用的时候没发现这个问题，是网页的参数发生了什么变化么orz — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
啊不好意思是，刚刚仔细看了一遍说明，是我太久没用自己犯傻了orz
 应该链接应该用页面下面的链接，我想当然地用了网页自己的URL = =
 重新试了一下，没有出现变化，可以正常下载，祝推研顺利！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
